# Generated by Django 4.2.1 on 2023-06-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('claveUsuario', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('file', models.ImageField(upload_to='Productos')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_chocolateria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaBoleta', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_chocolateria.producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_chocolateria.usuarios')),
            ],
        ),
    ]
